version: '3'
volumes:
  static:

services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ./config:/config
      - ./books:/books
      - static:/app/calibre-web/cps/static
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    image: calibre-nginx
    container_name: calibre-nginx
    volumes:
      - static:/static
      - ./web:/web
    ports:
      - 8083:8083

  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: my-syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./syncthing/:/var/syncthing/
      - ./books:/books 
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
    restart: unless-stopped
